### ISSUE TITLE
filter_entities should allow for multiple filters

### ISSUE THREAD

**Issue by raphael-melo** [ibm-hyperknowledge/hklib#7]
HKBase allows the following filters: 
- AND: `[{"properties": {"someProperty": "a"}}, {"properties": {"anotherProperty": "b"}}]`;
  - Returns entities with `"someProperty": "a"` **and** `"anotherProperty": "b"` properties;
- OR: `[[{"properties": {"someProperty": "a"}}], [{"properties": {"someProperty": "b"}}]]`
  - Returns entities with `"someProperty": "a"` **or** `"someProperty": "b"` properties;

https://github.com/ibm-hyperknowledge/hklib/blob/4807002e683b4f45151f1c68b7ef77928c86539f/datasource/hkdatasource.js#L442

**Comment by raphael-melo** [comment]
There isn't actually any bug here. In JavaScript, `typeof []` returns `object`, I thought that arrays were a more basic type. 😞 I'm closing this issue.

**Comment by wallashss** [comment]
Fine.

Just a hint, you can check if an _object_ is an array as follow:

```
Array.isArray(anObject);
```

https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray
